### ISSUE TITLE
link BigLabs from README.md

### ISSUE THREAD

**Issue by fulcorno** [polito-WA1-AW1-2021/course-materials#1]
ciao Luca, visto che hai caricato tutto il materiale sui BigLab nel repo, sarebbe utile linkare i file dal README.md (come facciamo per le slide e come abbiamo fatto per i primi 3 lab)

**Comment by LucaMannella** [comment]
Ciao Fulvio, fatto.
Ho aggiunto anche i file relativi al BigLab nel README.
